version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "today-law"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sbuesr2h4wx4"
s3_prefix = "today-law"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
